// <auto-generated />
namespace MvcmusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 初始化数据库 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(初始化数据库));
        
        string IMigrationMetadata.Id
        {
            get { return "201606051307140_初始化数据库"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
